#Get all hotels
GET http://localhost:7777/api/hotel

###

#Get hotel by id
GET http://localhost:7777/api/hotel/1

###

# Get a hotels rooms by it's id (not made )
GET http://localhost:7777/api/hotel/1/room

###

#create a hotel with rooms
POST http://localhost:7777/api/hotel
Content-Type: application/json

{
  "name": "Hotel 7",
  "address": "Address 8",
  "rooms": []
}

###

# updat
PUT http://localhost:7777/api/hotel/2
Content-Type: application/json

{
  "name": "SuperHotel 2"
}
###

#deleting a hotel by id
DELETE http://localhost:7777/api/hotel/3