#g Get all rooms
GET http://localhost:7777/api/room

###

#Get room by id : "http://localhost:7777/api/room/1"
GET {{URL}}
#Look in the http-client.json fil

###

#create rooms
POST {{STD}}
Content-Type: application/json

{
  "hotelId": 4,
  "number": 2,
  "price": 999
}

###

# updat
PUT http://localhost:7777/api/room/1
Content-Type: application/json

{
  "hotelId": 1,
  "number": 9,
  "price": 1300
}
###

#deleting a hotel by id
DELETE {{URL}}