GET http://localhost:7777/api/hotel

###

POST http://localhost:7777/api/hotel
Content-Type: application/json

{
  "name": "Hotel 3",
  "address": "Address 3",
  "rooms": [
    {
      "hotelId": 1,
      "number": 301,
      "price": 100
    },
    {
      "hotelId": 1,
      "number": 302,
      "price": 200
    }
  ]
}


###